const simpleGit = require('simple-git');
const fs = require('fs-extra');
const path = require('path');
const os = require('os');
const logger = require('../utils/logger').child('publish');

const PUBLIC_REPO = 'https://github.com/gautammanak1/ai-tech-daily.git';

const README_TEMPLATE = `# AI & Tech Daily

> Automated daily digest of AI, AI Agents, Web3, and tech news — generated by an AI agent, for developers.

---

## Latest Article

**Date:** {{DATE}}

Read the full article: **[article.md](./article.md)**

---

## About

This repository is updated daily by the [AI Tech Daily Agent](https://github.com/gautammanak1/ai-tech-daily-agent). Every morning, the agent:

1. Fetches news from 12+ sources (RSS, Hacker News, Dev.to, CoinDesk)
2. Filters and ranks AI/Web3/Agent-related content
3. Summarizes using an LLM
4. Generates a full newsletter with images
5. Publishes here automatically

---

## Support

If this project is useful, consider sponsoring: **[github.com/sponsors/gautammanak1](https://github.com/sponsors/gautammanak1)**
`;

async function publishToPublicRepo(articleContent, date) {
  const tmpDir = path.join(os.tmpdir(), `ai-tech-daily-publish-${Date.now()}`);

  try {
    logger.info(`Cloning public repo to ${tmpDir}...`);
    const git = simpleGit();

    const token = (process.env.GH_TOKEN || process.env.GITHUB_TOKEN || '').replace(/[\r\n\s]+/g, '');
    let cloneUrl = PUBLIC_REPO;
    if (token) {
      cloneUrl = PUBLIC_REPO.replace('https://', `https://x-access-token:${token}@`);
    }

    await git.clone(cloneUrl, tmpDir, ['--depth', '1']);

    const repoGit = simpleGit(tmpDir);
    const userName = process.env.GIT_USER_NAME || 'gautammanak1';
    const userEmail = process.env.GIT_USER_EMAIL || 'gautammanak1@gmail.com';
    await repoGit.addConfig('user.name', userName, false, 'local');
    await repoGit.addConfig('user.email', userEmail, false, 'local');

    await fs.writeFile(path.join(tmpDir, 'article.md'), articleContent, 'utf-8');

    const readme = README_TEMPLATE.replace('{{DATE}}', date);
    await fs.writeFile(path.join(tmpDir, 'README.md'), readme, 'utf-8');

    const imagesDir = path.resolve(process.cwd(), 'images');
    if (await fs.pathExists(imagesDir)) {
      await fs.copy(imagesDir, path.join(tmpDir, 'images'), { overwrite: true });
      logger.info('Images copied to public repo');
    }

    await repoGit.add('-A');

    const status = await repoGit.status();
    if (status.staged.length === 0) {
      logger.info('No changes to publish — already up to date');
      return;
    }

    await repoGit.commit(`docs: update AI trends — ${date}`);
    await repoGit.push('origin', 'main');
    logger.info('Article + README published to public repo');
  } catch (err) {
    logger.error(`Failed to publish to public repo: ${err.message}`);
  } finally {
    await fs.remove(tmpDir).catch(() => {});
  }
}

module.exports = { publishToPublicRepo };
