"""Publish articles to Dev.to automatically via their API."""

import logging
import os
import re

import requests

log = logging.getLogger("devto")

DEVTO_API = "https://dev.to/api/articles"

COMPANY_TAG_MAP = {
    "google": "google", "microsoft": "microsoft", "apple": "apple",
    "amazon": "aws", "meta": "meta", "nvidia": "nvidia", "openai": "openai",
    "anthropic": "ai", "huggingface": "huggingface", "langchain": "langchain",
    "fetchai": "fetchai", "crewai": "ai", "composio": "ai",
}

DEFAULT_TAGS = ["ai", "machinelearning", "programming", "technology"]


def _get_api_key() -> str | None:
    return (os.getenv("DEVTO_API_KEY") or "").strip() or None


def _extract_title(article: str) -> str:
    """Pull the first H1 from the markdown, fallback to generic."""
    match = re.search(r"^#\s+(.+)$", article, re.MULTILINE)
    if match:
        title = match.group(1).strip()
        title = re.sub(r"\s*\|.*$", "", title)
        return title[:128]
    return "AI & Tech Daily Deep Dive"


def _pick_tags(company_slug: str) -> list[str]:
    """Pick up to 4 tags — Dev.to max is 4."""
    tags = []
    mapped = COMPANY_TAG_MAP.get(company_slug.lower().replace(" ", ""))
    if mapped and mapped not in tags:
        tags.append(mapped)

    for t in DEFAULT_TAGS:
        if t not in tags:
            tags.append(t)
        if len(tags) >= 4:
            break
    return tags[:4]


def _clean_for_devto(article: str) -> str:
    """Strip leading H1 (Dev.to uses title field) and clean up for the platform."""
    lines = article.split("\n")
    cleaned = []
    skipped_title = False
    for line in lines:
        if not skipped_title and re.match(r"^#\s+", line):
            skipped_title = True
            continue
        cleaned.append(line)

    body = "\n".join(cleaned).strip()

    body += "\n\n---\n\n*This article was auto-generated by [AI Tech Daily Agent](https://github.com/gautammanak1/ai-tech-daily-agent) — an autonomous Fetch.ai uAgent that researches and writes daily deep-dives.*\n"
    return body


def publish_to_devto(
    article_content: str,
    company_name: str,
    company_slug: str,
    series: str = "AI Tech Daily",
    published: bool = True,
) -> str | None:
    """Post article to Dev.to. Returns the published URL or None on failure."""
    api_key = _get_api_key()
    if not api_key:
        log.warning("DEVTO_API_KEY not set — skipping Dev.to publish")
        return None

    title = _extract_title(article_content)
    tags = _pick_tags(company_slug)
    body = _clean_for_devto(article_content)

    canonical_url = f"https://github.com/gautammanak1/ai-tech-daily"

    payload = {
        "article": {
            "title": title,
            "published": published,
            "body_markdown": body,
            "tags": tags,
            "series": series,
            "canonical_url": canonical_url,
            "description": f"A comprehensive deep-dive into {company_name} — latest news, products, code examples, and what it means for developers.",
        }
    }

    headers = {
        "api-key": api_key,
        "Content-Type": "application/json",
        "User-Agent": "AI-Tech-Daily-Agent/1.0",
    }

    try:
        resp = requests.post(DEVTO_API, json=payload, headers=headers, timeout=30)
        if resp.status_code == 201:
            data = resp.json()
            url = data.get("url", "")
            log.info(f"Published to Dev.to: {url}")
            return url
        else:
            log.error(f"Dev.to API error {resp.status_code}: {resp.text[:500]}")
            return None
    except Exception as e:
        log.error(f"Dev.to publish failed: {e}")
        return None
