"""Publish article to public GitHub repo without overwriting old content."""

import logging
import os
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

log = logging.getLogger("publish")

PUBLIC_REPO = "https://github.com/gautammanak1/ai-tech-daily.git"


def _get_available_filename(date_str: str, output_dir: str) -> str:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    base = f"{date_str}.md"
    if not (out / base).exists():
        return base

    for i in range(2, 50):
        name = f"{date_str}-{i}.md"
        if not (out / name).exists():
            log.info(f"{base} exists — using {name}")
            return name
    return base


def save_article(content: str, date_str: str, output_dir: str = "articles") -> tuple[str, str]:
    filename = _get_available_filename(date_str, output_dir)
    filepath = Path(output_dir) / filename
    filepath.write_text(content, encoding="utf-8")
    log.info(f"Article saved: {filepath}")
    return filename, str(filepath)


def commit_and_push(filepath: str, date_str: str, dry_run: bool = False):
    if dry_run:
        log.info("DRY_RUN — skipping git commit")
        return

    try:
        from git import Repo
        repo = Repo(".")
        repo.config_writer().set_value("user", "name", os.getenv("GIT_USER_NAME", "gautammanak1")).release()
        repo.config_writer().set_value("user", "email", os.getenv("GIT_USER_EMAIL", "gautammanak1@gmail.com")).release()

        repo.git.add(filepath)
        repo.git.add("images/")
        repo.index.commit(f"docs: add AI trends article for {date_str}")
        repo.git.pull("origin", "main", rebase="true")
        repo.remotes.origin.push()
        log.info("Committed and pushed to private repo")
    except Exception as e:
        log.error(f"Git push failed: {e}")


def publish_to_public_repo(article_content: str, date_str: str):
    token = os.getenv("GH_TOKEN", "").strip()
    if not token:
        token = os.getenv("GITHUB_TOKEN", "").strip()

    clone_url = PUBLIC_REPO
    if token:
        clone_url = PUBLIC_REPO.replace("https://", f"https://x-access-token:{token}@")

    tmp_dir = tempfile.mkdtemp(prefix="ai-tech-daily-")

    try:
        from git import Repo
        log.info(f"Cloning public repo...")
        repo = Repo.clone_from(clone_url, tmp_dir, depth=1)
        repo.config_writer().set_value("user", "name", os.getenv("GIT_USER_NAME", "gautammanak1")).release()
        repo.config_writer().set_value("user", "email", os.getenv("GIT_USER_EMAIL", "gautammanak1@gmail.com")).release()

        (Path(tmp_dir) / "article.md").write_text(article_content, encoding="utf-8")

        _update_readme(tmp_dir, date_str)

        images_src = Path("images")
        if images_src.exists():
            images_dst = Path(tmp_dir) / "images"
            if images_dst.exists():
                shutil.rmtree(images_dst)
            shutil.copytree(images_src, images_dst)
            log.info("Images copied to public repo")

        repo.git.add("-A")
        if repo.is_dirty() or repo.untracked_files:
            repo.index.commit(f"docs: update AI trends — {date_str}")
            repo.remotes.origin.push()
            log.info("Published to public repo")
        else:
            log.info("No changes to publish")
    except Exception as e:
        log.error(f"Failed to publish: {e}")
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def _update_readme(repo_dir: str, date_str: str):
    readme_path = Path(repo_dir) / "README.md"

    readme = f"""# AI & Tech Daily

> Automated daily digest of AI, AI Agents, Web3, and tech news — generated by an AI agent, for developers.

---

## Latest Article

**Date:** {date_str}

Read the full article: **[article.md](./article.md)**

---

## About

This repository is updated daily by the [AI Tech Daily Agent](https://github.com/gautammanak1/ai-tech-daily-agent). Every morning, the agent:

1. Fetches news from 12+ sources (RSS, Hacker News, Dev.to, CoinDesk)
2. Filters and ranks AI/Web3/Agent-related content
3. Summarizes using an LLM
4. Generates a full newsletter with images
5. Publishes here automatically

---

## Support

If this project is useful, consider sponsoring: **[github.com/sponsors/gautammanak1](https://github.com/sponsors/gautammanak1)**
"""
    readme_path.write_text(readme, encoding="utf-8")
